export const $ = {
  titleInput:     document.getElementById('field-title'),
  descInput:      document.getElementById('field-description'),
  locationInput:  document.getElementById('field-location'),
  addedByInput:   document.getElementById('field-added-by'),
  submitBtn:      document.getElementById('submit-btn'),
  submitError:    document.getElementById('submit-error'),
  watermark:      document.getElementById('form-watermark'),
  overlay:        document.getElementById('animation-overlay'),
  animEnvelope:   document.getElementById('anim-envelope'),
  animBox:        document.getElementById('anim-box'),
  animHearts:     document.getElementById('anim-hearts'),
  archiveToggle:  document.getElementById('archive-toggle'),
  topPicksList:   document.getElementById('top-picks-list'),
  theBoxList:     document.getElementById('the-box-list'),
  archiveList:    document.getElementById('archive-list'),
  topPicksEmpty:  document.getElementById('top-picks-empty'),
  theBoxEmpty:    document.getElementById('the-box-empty'),
  archiveEmpty:   document.getElementById('archive-empty'),
  archiveCount:   document.getElementById('archive-count'),
  submissionCard: document.getElementById('submission-card'),
  appMain:        document.getElementById('app-main'),
};
